import * as React from 'react';

import Antifonas from '../liturgia/fiestasSolemnidades/textos/antifonas.json';
import CanticoEvangelico from '../liturgia/fiestasSolemnidades/textos/canticoEvangelico.json';
import Himnos from '../liturgia/fiestasSolemnidades/textos/himnos.json';
import Lecturas from '../liturgia/fiestasSolemnidades/textos/leturas.json';
import OracionFinal from '../liturgia/fiestasSolemnidades/textos/oracionFinal.json';
import Preces from '../liturgia/fiestasSolemnidades/textos/preces.json';
import Responsorio from '../liturgia/fiestasSolemnidades/textos/responsorios.json';
import Salmos from '../liturgia/fiestasSolemnidades/textos/salmos.json';
import TitulosCelebraciones from '../liturgia/fiestasSolemnidades/textos/titulosCelebraciones.json';



// AQUI SE construyen los contenidos de cada día de los Laudes y Visperas//
export const traslacionLaudes = {
    partes : [
        TitulosCelebraciones.titulo1,
        TitulosCelebraciones.laudes,
        Himnos.himno,
        Himnos.himnoTitulo1,
        Himnos.himnoCuerpo1,
        Antifonas.salmodia,
        Antifonas.antifona4,
        Antifonas.cuerpoAntifona4,
        Salmos.numeroSalmo62,
        Salmos.tituloSalmo62,
        Salmos.cuerpoSalmo62,
        Antifonas.antifona4,
        Antifonas.cuerpoAntifona4,
        Antifonas.antifona5,
        Antifonas.cuerpoAntifona5,
        Salmos.numeroSalmoDaniel3,
        Salmos.tituloSalmoDaniel3,
        Salmos.cuerpoSalmoDaniel3,
        Antifonas.antifona5,
        Antifonas.cuerpoAntifona5,
        Antifonas.antifona6,
        Antifonas.cuerpoAntifona6,
        Salmos.numeroSalmo149,
        Salmos.tituloSalmo149,
        Salmos.cuerpoSalmo149,
        Antifonas.antifona6,
        Antifonas.cuerpoAntifona6,
        Lecturas.lecturaBreve,
        Lecturas.tituloLecturaBreve1,
        Lecturas.cuerpoLecturaBreve1,
        Responsorio.responsorioBreve,
        Responsorio.versiculoResponsorioBreve1,
        Responsorio.respuestaResponsorioBreve1,
        Responsorio.versiculoResponsorioBreve2,
        Responsorio.respuestaResponsorioBreve2,
        Responsorio.versiculoResponsorioBreve3,
        Responsorio.respuestaResponsorioBreve3,
        CanticoEvangelico.canticoEvangelico,
        CanticoEvangelico.cuerpoAntifonaCanticoEvangelico1,
        CanticoEvangelico.tituloCanticoEvangelicoBenedictus,
        CanticoEvangelico.subtituloCanticoEvangelicoBenedictus,
        CanticoEvangelico.cuerpoCanticoEvangelicoBenedictus,
        CanticoEvangelico.cuerpoAntifonaCanticoEvangelico1,
        Preces.preces,
        Preces.cuerpoPreces1,
        OracionFinal.oracion,
        OracionFinal.oracionCuerpo1,
        OracionFinal.bendicionFinal,
        OracionFinal.cuerpoBendicionFinal1,
        OracionFinal.ultimaOracion1,
        OracionFinal.cuerpoUltimaOracion1              
    ]
};

export const traslacionVisperas = {
    partes : [
        TitulosCelebraciones.titulo1,
        TitulosCelebraciones.visperas2,
        Himnos.himno,
        Himnos.himnoTitulo2,
        Himnos.himnoCuerpo2,
        Antifonas.salmodia,
        Antifonas.antifona7,
        Antifonas.cuerpoAntifona7,
        Salmos.numeroSalmo115,
        Salmos.tituloSalmo115,
        Salmos.cuerpoSalmo115,
        Antifonas.antifona7,
        Antifonas.cuerpoAntifona7,
        Antifonas.antifona8,
        Antifonas.cuerpoAntifona8,
        Salmos.numeroSalmo125,
        Salmos.tituloSalmo125,
        Salmos.cuerpoSalmo125,
        Antifonas.antifona8,
        Antifonas.cuerpoAntifona8,
        Antifonas.antifona9,
        Antifonas.cuerpoAntifona9,
        Salmos.numeroSalmoEfesios1,
        Salmos.tituloSalmoEfesios1,
        Salmos.cuerpoSalmoEfesios1,
        Antifonas.antifona9,
        Antifonas.cuerpoAntifona9,
        Lecturas.lecturaBreve,
        Lecturas.tituloLecturaBreve2,
        Lecturas.cuerpoLecturaBreve2,
        Responsorio.responsorioBreve,
        Responsorio.versiculoResponsorioBreve4,
        Responsorio.respuestaResponsorioBreve4,
        Responsorio.versiculoResponsorioBreve5,
        Responsorio.respuestaResponsorioBreve5,
        Responsorio.versiculoResponsorioBreve6,
        Responsorio.respuestaResponsorioBreve6,
        CanticoEvangelico.canticoEvangelico,
        CanticoEvangelico.cuerpoAntifonaCanticoEvangelico2,
        CanticoEvangelico.tituloCanticoEvangelicoMagnificat,
        CanticoEvangelico.subtituloCanticoEvangelicoMagnificat,
        CanticoEvangelico.cuerpoCanticoEvangelicoMagnificat,
        CanticoEvangelico.cuerpoAntifonaCanticoEvangelico2,
        Preces.preces,
        Preces.cuerpoPreces2,
        OracionFinal.oracion,
        OracionFinal.oracionCuerpo2,
        OracionFinal.bendicionFinal,
        OracionFinal.cuerpoBendicionFinal2,
        OracionFinal.ultimaOracion2,
        OracionFinal.cuerpoUltimaOracion2         
    ]
};

export const solemnidadVisperas1 = {
    partes : [
        TitulosCelebraciones.titulo2,
        TitulosCelebraciones.visperas1,
        Himnos.himno,
        Himnos.himnoTitulo3,
        Himnos.himnoCuerpo3,
        Antifonas.salmodia,
        Antifonas.antifona1,
        Antifonas.cuerpoAntifona1,
        Salmos.numeroSalmo95,
        Salmos.tituloSalmo95,
        Salmos.cuerpoSalmo95,
        Antifonas.antifona1,
        Antifonas.cuerpoAntifona1,
        Antifonas.antifona2,
        Antifonas.cuerpoAntifona2,
        Salmos.numeroSalmo97,
        Salmos.tituloSalmo97,
        Salmos.cuerpoSalmo97,
        Antifonas.antifona2,
        Antifonas.cuerpoAntifona3,
        Antifonas.antifona3,
        Antifonas.cuerpoAntifona9,
        Salmos.numeroSalmoEfesios1,
        Salmos.tituloSalmoEfesios1,
        Salmos.cuerpoSalmoEfesios1,
        Antifonas.antifona3,
        Antifonas.cuerpoAntifona3,
        Lecturas.lecturaBreve,
        Lecturas.tituloLecturaBreve3,
        Lecturas.cuerpoLecturaBreve3,
        Responsorio.responsorioBreve,
        Responsorio.versiculoResponsorioBreve7,
        Responsorio.respuestaResponsorioBreve7,
        Responsorio.versiculoResponsorioBreve8,
        Responsorio.respuestaResponsorioBreve8,
        Responsorio.versiculoResponsorioBreve9,
        Responsorio.respuestaResponsorioBreve9,
        CanticoEvangelico.canticoEvangelico,
        CanticoEvangelico.cuerpoAntifonaCanticoEvangelico3,
        CanticoEvangelico.tituloCanticoEvangelicoMagnificat,
        CanticoEvangelico.subtituloCanticoEvangelicoMagnificat,
        CanticoEvangelico.cuerpoCanticoEvangelicoMagnificat,
        CanticoEvangelico.cuerpoAntifonaCanticoEvangelico3,
        Preces.preces,
        Preces.cuerpoPreces3,
        OracionFinal.oracion,
        OracionFinal.oracionCuerpo3,
        OracionFinal.bendicionFinal,
        OracionFinal.cuerpoBendicionFinal3,
        OracionFinal.ultimaOracion3,
        OracionFinal.cuerpoUltimaOracion3         
    ]
};

export const solemnidadLaudes = {
    partes : [
        TitulosCelebraciones.titulo2,
        TitulosCelebraciones.laudes,
        Himnos.himno,
        Himnos.himnoTitulo1,
        Himnos.himnoCuerpo1,
        Antifonas.salmodia,
        Antifonas.antifona4,
        Antifonas.cuerpoAntifona4,
        Salmos.numeroSalmo62,
        Salmos.tituloSalmo62,
        Salmos.cuerpoSalmo62,
        Antifonas.antifona4,
        Antifonas.cuerpoAntifona4,
        Antifonas.antifona5,
        Antifonas.cuerpoAntifona5,
        Salmos.numeroSalmoDaniel3,
        Salmos.tituloSalmoDaniel3,
        Salmos.cuerpoSalmoDaniel3,
        Antifonas.antifona5,
        Antifonas.cuerpoAntifona5,
        Antifonas.antifona6,
        Antifonas.cuerpoAntifona6,
        Salmos.numeroSalmo149,
        Salmos.tituloSalmo149,
        Salmos.cuerpoSalmo149,
        Antifonas.antifona6,
        Antifonas.cuerpoAntifona6,
        Lecturas.lecturaBreve,
        Lecturas.tituloLecturaBreve4,
        Lecturas.cuerpoLecturaBreve4,
        Responsorio.responsorioBreve,
        Responsorio.versiculoResponsorioBreve1,
        Responsorio.respuestaResponsorioBreve1,
        Responsorio.versiculoResponsorioBreve2,
        Responsorio.respuestaResponsorioBreve2,
        Responsorio.versiculoResponsorioBreve3,
        Responsorio.respuestaResponsorioBreve3,
        CanticoEvangelico.canticoEvangelico,
        CanticoEvangelico.cuerpoAntifonaCanticoEvangelico4,
        CanticoEvangelico.tituloCanticoEvangelicoBenedictus,
        CanticoEvangelico.subtituloCanticoEvangelicoBenedictus,
        CanticoEvangelico.cuerpoCanticoEvangelicoBenedictus,
        CanticoEvangelico.cuerpoAntifonaCanticoEvangelico4,
        Preces.preces,
        Preces.cuerpoPreces1,
        OracionFinal.oracion,
        OracionFinal.oracionCuerpo1,
        OracionFinal.bendicionFinal,
        OracionFinal.cuerpoBendicionFinal1,
        OracionFinal.ultimaOracion1,
        OracionFinal.cuerpoUltimaOracion1              
    ]
};

export const solemnidadVisperas2 = {
    partes : [
        TitulosCelebraciones.titulo2,
        TitulosCelebraciones.visperas2,
        Himnos.himno,
        Himnos.himnoTitulo2,
        Himnos.himnoCuerpo2,
        Antifonas.salmodia,
        Antifonas.antifona7,
        Antifonas.cuerpoAntifona7,
        Salmos.numeroSalmo115,
        Salmos.tituloSalmo115,
        Salmos.cuerpoSalmo115,
        Antifonas.antifona7,
        Antifonas.cuerpoAntifona7,
        Antifonas.antifona8,
        Antifonas.cuerpoAntifona8,
        Salmos.numeroSalmo125,
        Salmos.tituloSalmo125,
        Salmos.cuerpoSalmo125,
        Antifonas.antifona8,
        Antifonas.cuerpoAntifona8,
        Antifonas.antifona9,
        Antifonas.cuerpoAntifona9,
        Salmos.numeroSalmoEfesios1,
        Salmos.tituloSalmoEfesios1,
        Salmos.cuerpoSalmoEfesios1,
        Antifonas.antifona9,
        Antifonas.cuerpoAntifona9,
        Lecturas.lecturaBreve,
        Lecturas.tituloLecturaBreve2,
        Lecturas.cuerpoLecturaBreve2,
        Responsorio.responsorioBreve,
        Responsorio.versiculoResponsorioBreve13,
        Responsorio.respuestaResponsorioBreve13,
        Responsorio.versiculoResponsorioBreve14,
        Responsorio.respuestaResponsorioBreve14,
        Responsorio.versiculoResponsorioBreve15,
        Responsorio.respuestaResponsorioBreve15,
        CanticoEvangelico.canticoEvangelico,
        CanticoEvangelico.cuerpoAntifonaCanticoEvangelico2,
        CanticoEvangelico.tituloCanticoEvangelicoMagnificat,
        CanticoEvangelico.subtituloCanticoEvangelicoMagnificat,
        CanticoEvangelico.cuerpoCanticoEvangelicoMagnificat,
        CanticoEvangelico.cuerpoAntifonaCanticoEvangelico2,
        Preces.preces,
        Preces.cuerpoPreces2,
        OracionFinal.oracion,
        OracionFinal.oracionCuerpo3,
        OracionFinal.bendicionFinal,
        OracionFinal.cuerpoBendicionFinal3,
        OracionFinal.ultimaOracion3,
        OracionFinal.cuerpoUltimaOracion3         
    ]
};


